# server 
server:
  port: 8081
  servlet:
     context-path: /api/auth
  
# Secret Key
app:
  secretKey: '[@q2Xg7@T4mOplFu#Ae]'
  jwtValidityMinutes: 30
  
# spring 
spring:
  application:
    name: auth-service
    
# Database
  datasource:
    url: jdbc:h2:mem:authentication_db
    username: jugraj
    password: jugraj
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
   console:
     enabled: true
     settings:
       web-allow-others: true
      
# Error Messages
jwtUtil:
  expiredMessage: Token has been expired
  malformedMessage: Token is in invalid format
  signatureMessage: Token signature is invalid
  nullOrEmptyMessage: Token is either null or empty
  unsupportedMessage: Claims for token is not supported
  
userDetails:
  errorMessage: Incorrect Credentials ! Try again
  badCredentialsMessage: Incorrect Credentials ! Try again
 
logging:
 level:
    '[org.springframework.web]': ERROR
    '[com.cts.processPension]': DEBUG       