version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:854585762102:task-definition/auth-service:1"
        LoadBalancerInfo:
          ContainerName: "auth-service"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"
