version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::SERVICE
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:854585762102:task-definition/auth-service:2"
        LoadBalancerInfo:
          ContainerName: "auth-service"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"
     